import { useState } from 'react';
import { SearchIcon } from '../icons/CategoryIcons';

const glossaryTerms = [
    { term: "SPF", category: "Authentication", preview: "Sender Policy Framework - Lists authorized mail servers for your domain" },
    { term: "DKIM", category: "Authentication", preview: "DomainKeys Identified Mail - Digital signature verifying email integrity" },
    { term: "DMARC", category: "Authentication", preview: "Domain-based Message Authentication - Policy for handling failed checks" },
    { term: "BIMI", category: "Authentication", preview: "Brand Indicators for Message Identification - Display your logo in inboxes" },
    { term: "Open Rate", category: "Metrics", preview: "Percentage of recipients who opened your email" },
    { term: "Click-Through Rate", category: "Metrics", preview: "Percentage of recipients who clicked a link in your email" },
    { term: "Bounce Rate", category: "Metrics", preview: "Percentage of emails that couldn't be delivered" },
    { term: "Hard Bounce", category: "Deliverability", preview: "Permanent delivery failure (invalid email address)" },
    { term: "Soft Bounce", category: "Deliverability", preview: "Temporary delivery failure (full inbox, server down)" },
    { term: "Spam Trap", category: "Deliverability", preview: "Email address used to catch spammers" },
    { term: "Sender Score", category: "Reputation", preview: "Numerical rating of your email sending reputation" },
    { term: "IP Warming", category: "Deliverability", preview: "Gradually increasing send volume on a new IP" },
    { term: "List Hygiene", category: "Best Practices", preview: "Regularly cleaning your email list of invalid addresses" },
    { term: "Double Opt-in", category: "Best Practices", preview: "Confirmation email to verify subscriber intent" },
    { term: "CAN-SPAM", category: "Compliance", preview: "US law governing commercial email requirements" },
    { term: "GDPR", category: "Compliance", preview: "EU regulation on data protection and privacy" },
    { term: "A/B Testing", category: "Optimization", preview: "Testing two versions to see which performs better" },
    { term: "Personalization", category: "Strategy", preview: "Tailoring email content to individual recipients" },
    { term: "Segmentation", category: "Strategy", preview: "Dividing your list into targeted groups" },
    { term: "Automation", category: "Strategy", preview: "Triggered emails based on subscriber actions" }
];

export const Glossary: React.FC = () => {
    const [searchQuery, setSearchQuery] = useState('');
    const [selectedTerm, setSelectedTerm] = useState<string | null>(null);
    const [explanation, setExplanation] = useState<{ simple: string; detailed: string; example: string } | null>(null);
    const [isLoading, setIsLoading] = useState(false);

    const filteredTerms = glossaryTerms.filter(item =>
        item.term.toLowerCase().includes(searchQuery.toLowerCase()) ||
        item.category.toLowerCase().includes(searchQuery.toLowerCase()) ||
        item.preview.toLowerCase().includes(searchQuery.toLowerCase())
    );

    const categories = [...new Set(glossaryTerms.map(t => t.category))];

    const handleTermClick = async (term: string) => {
        setSelectedTerm(term);
        setIsLoading(true);
        
        try {
            const response = await fetch('/api/glossary/explain', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ term })
            });
            
            if (response.ok) {
                const data = await response.json();
                setExplanation({
                    simple: data.simpleDefinition,
                    detailed: data.detailedExplanation,
                    example: data.practicalExample
                });
            } else {
                const termData = glossaryTerms.find(t => t.term === term);
                setExplanation({
                    simple: termData?.preview || '',
                    detailed: 'Full AI-powered explanation would appear here when connected to the API.',
                    example: 'A practical example would be generated by AI.'
                });
            }
        } catch (error) {
            const termData = glossaryTerms.find(t => t.term === term);
            setExplanation({
                simple: termData?.preview || '',
                detailed: 'Full AI-powered explanation would appear here when connected to the API.',
                example: 'A practical example would be generated by AI.'
            });
        } finally {
            setIsLoading(false);
        }
    };

    return (
        <div className="space-y-6 animate-fade-in">
            <div>
                <h3 className="text-2xl font-bold text-white mb-2">AI-Powered Glossary</h3>
                <p className="text-gray-400">Click any term to get an AI-generated explanation with practical examples.</p>
            </div>

            <div className="relative">
                <SearchIcon className="absolute left-3 top-1/2 transform -translate-y-1/2 w-5 h-5 text-gray-500" />
                <input
                    type="text"
                    value={searchQuery}
                    onChange={(e) => setSearchQuery(e.target.value)}
                    placeholder="Search terms..."
                    className="w-full bg-gray-900/50 border border-gray-600 rounded-lg pl-10 pr-4 py-3 text-white placeholder-gray-500 input-glow-focus outline-none"
                    data-testid="input-glossary-search"
                />
            </div>

            <div className="grid md:grid-cols-2 gap-6">
                <div className="space-y-4">
                    {categories.map(category => {
                        const categoryTerms = filteredTerms.filter(t => t.category === category);
                        if (categoryTerms.length === 0) return null;
                        
                        return (
                            <div key={category}>
                                <h4 className="text-sm font-semibold text-purple-400 uppercase tracking-wider mb-2">{category}</h4>
                                <div className="space-y-1">
                                    {categoryTerms.map(item => (
                                        <button
                                            key={item.term}
                                            onClick={() => handleTermClick(item.term)}
                                            className={`w-full text-left p-3 rounded-lg border transition-all ${
                                                selectedTerm === item.term
                                                    ? 'bg-purple-600/30 border-purple-500'
                                                    : 'bg-white/5 border-white/10 hover:bg-white/10'
                                            }`}
                                        >
                                            <div className="font-semibold text-white">{item.term}</div>
                                            <div className="text-xs text-gray-400 mt-1">{item.preview}</div>
                                        </button>
                                    ))}
                                </div>
                            </div>
                        );
                    })}
                </div>

                <div className="bg-white/5 p-6 rounded-lg border border-white/10 sticky top-0">
                    {!selectedTerm ? (
                        <div className="text-center text-gray-400 py-8">
                            <p>Select a term to see its AI-powered explanation</p>
                        </div>
                    ) : isLoading ? (
                        <div className="text-center py-8">
                            <div className="animate-spin h-8 w-8 border-2 border-purple-500 border-t-transparent rounded-full mx-auto mb-4"></div>
                            <p className="text-gray-400">Generating explanation...</p>
                        </div>
                    ) : explanation ? (
                        <div className="space-y-4 animate-fade-in">
                            <div>
                                <h4 className="text-xl font-bold text-white">{selectedTerm}</h4>
                                <p className="text-purple-300 mt-1">{explanation.simple}</p>
                            </div>
                            <div>
                                <h5 className="font-semibold text-gray-200 mb-2">Detailed Explanation</h5>
                                <p className="text-gray-400 text-sm leading-relaxed">{explanation.detailed}</p>
                            </div>
                            <div className="bg-purple-900/30 border border-purple-500/50 rounded-lg p-4">
                                <h5 className="font-semibold text-purple-300 mb-2">Practical Example</h5>
                                <p className="text-gray-300 text-sm">{explanation.example}</p>
                            </div>
                        </div>
                    ) : null}
                </div>
            </div>
        </div>
    );
};
