// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/acceptafy-redesign/Dashboard.tsx": () => import("../components/mockups/acceptafy-redesign/Dashboard.tsx"),
  "./components/mockups/acceptafy-redesign/Grader.tsx": () => import("../components/mockups/acceptafy-redesign/Grader.tsx")
};
